version: '3'

name: careers
services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.25.4
    networks:
      - careers_network
    environment:
      - TZ=Asia/Seoul
      - TIMEZONE=Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/careers/log/nginx:/var/log/nginx
      - /srv/careers/nginx/conf.d:/etc/nginx/conf.d

  mysql:
    container_name: mysql
    image: mysql:8.0.26
    networks:
      - careers_network
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: careers
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - /srv/careers/data/mysql/data:/var/lib/mysql
      - /srv/careers/data/mysql/conf.d:/etc/mysql/conf.d

  job:
    container_name: job_8080
    image: kyunkim/careers:job-0.0
    networks:
      - careers_network
    environment:
      JAR_FILE: 'job-1.0.0.jar'
      PROFILE: 'dev'
      JASYPT_PASSWORD: ''
    ports:
      - "${JOB_APP_PORT}:8080"
    depends_on:
      - mysql

networks:
  careers_network:
    driver: bridge
