version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: careers
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - C:/data/docker/mysql/careers/data:/var/lib/mysql
      - C:/data/docker/mysql/careers/conf.d:/etc/mysql/conf.d
