project:
  properties:
#    secret-key: C:/kyunkim/project/level-up/firebase/level-up-516d8-firebase-adminsdk-2ffux-dc6b1f5357.json
    secret-key: C:/Task/project/level-up/tools/firebase/level-up-516d8-firebase-adminsdk-2ffux-dc6b1f5357.json
    firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"
    firebase-topic: "diet_record_notification"

api_base_url: http://localhost:8080
