server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/levelup?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

webdriver:
  chrome:
    driver: C:\Task\tools\chromedriver_win32\chromedriver.exe

project:
  properties:
    secret-key: firebase/level-up-516d8-firebase-adminsdk-2ffux-dc6b1f5357.json
    firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"
    firebase-topic: "diet_record_notification"

baseurl: http://localhost:8080
