server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://level-up-database.cdbjs5p1unct.ap-northeast-2.rds.amazonaws.com:3306/levelup?serverTimezone=Asia/Seoul
    username: root
    password: leveluprds!

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

webdriver:
  chrome:
    driver: /home/ec2-user/level-up/tools/chromedriver/chromedriver.exe

project:
  properties:
    firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"
    firebase-topic: "diet_record_notification"

baseurl: http://localhost:8080
