server:
  port: 8888

webdriver:
  chrome:
    driver: C:\tools\chromedriver_win32\chromedriver.exe
#    driver: C:\Task\tools\chromedriver_win32\chromedriver.exe

jwt:
  access-token:
    expiration: 10080 #분 단위

job:
  url: http://localhost:8080
