server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://level-up-database.cdbjs5p1unct.ap-northeast-2.rds.amazonaws.com:3306/levelup?serverTimezone=Asia/Seoul
    username: root
    password: leveluprds!

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

webdriver:
  chrome:
    driver: /home/ec2-user/level-up/tools/chromedriver/chromedriver

logging:
  config: classpath:log/logback-prod.xml

jwt:
  access-token:
    expiration: 10080 #분 단위

api_base_url: https://levelupback.link:8080
